service: karate

frameworkVersion: ">=1.13.2 <2.0.0"

provider:
  name: aws
  stage: dev
  runtime: nodejs6.10
  region: eu-west-1

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

functions:
  codewarsKatas:
    handler: handler.scrape_katas
    memorySize: 512
    timeout: 300
    events:
      - http:
          path: scrape/codewars/katas
          method: post
          cors: true

  duolingoProfile:
    handler: handler.scrape_duolingo
    memorySize: 512
    timeout: 300
    events:
      - http:
          path: scrape/duolingo/profile
          method: post
          cors: true
