service: karate

frameworkVersion: ">=1.14.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 1024
  timeout: 30
  apiKeys:
    - ${file(./project.yml):apiKey

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

functions:
  codewarsKatas:
    handler: handler.scrape_katas
    events:
      - http:
          method: post
          path: katas
          cors: true
          private: true

  duolingoProfile:
    handler: handler.scrape_duolingo
    events:
      - http:
          method: post
          path: duolingo
          cors: true
          private: true
