service: karate

frameworkVersion: ">=1.14.0 <2.0.0"

provider:
  name: google
  runtime: nodejs
  project: ${file(./project.yml):project}
  credentials: .gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions
  - serverless-webpack

custom:
  webpackIncludeModules: true

functions:
  codewarsKatas:
    handler: scrape_katas
    events:
      - http: path

  duolingoProfile:
    handler: scrape_duolingo
    events:
      - http: path
