service: karate

provider:
  name: google
  runtime: nodejs
  project: ${file(./project.yml):project}
  credentials: .gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions
  - serverless-webpack
custom:
  webpackIncludeModules: true

functions:
  codewars:
    memorySize: 1024
    timeout: 60
    handler: scrape_katas
    events:
      - http: /katas
