service:
  name: karate-scraper

plugins:
  - serverless-webpack

custom:
  webpack: '../../../webpack.config.js'
  webpackIncludeModules:
    packagePath: '../../../package.json'
  prefix: ${self:custom.stage}-${self:service}
  stage: ${opt:stage, self:provider.stage}
  task_table: ${self:custom.prefix}-task
  versions-prod: true
  versions-default: false

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  stage: test
  versionFunctions: ${self:custom.versions-${self:custom.stage}, self:custom.versions-default}
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:*
      Resource: arn:aws:dynamodb:*:*:table/*
  environment:
    region: ${self:provider.region}
    stage: ${self:custom.stage}
    task_table: ${self:custom.task_table}
    task_stream: ${file(./config.yml):task_stream}

functions:
  scrape:
    handler: handler.scrape
    timeout: 300
    memorySize: 1536
    events:
      - stream: ${self:provider.environment.task_stream}

  addTask:
    handler: handler.addTask
    name: ${self:custom.prefix}-addTask
    events:
      - http:
          method: post
          path: tasks
          cors: true

  getResult:
    handler: handler.getResult
    name: ${self:custom.prefix}-getResult
    events:
      - http:
          method: get
          path: results/{id}
          cors: true

  findExpression:
    handler: handler.findExpression
    name: ${self:custom.prefix}-findExpression
    events:
      - http:
          method: post
          path: expression
          cors: true

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.task_table}
        KeySchema:
          -
            AttributeName: task_id
            KeyType: HASH
        AttributeDefinitions:
          -
            AttributeName: task_id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
