service: karate-scraper

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  stage: test
  environment:
    region: ${self:provider.region}
    stage: ${self:custom.stage}

plugins:
  - serverless-webpack

custom:
  stream: ${file(../../config.yml):db_arn}
  stage: ${opt:stage, self:provider.stage}
  webpack: '../../webpack.config.js'
  webpackIncludeModules:
    packagePath: '../../package.json'

functions:
  scrape:
    handler: handler.scrape
    timeout: 300
    memorySize: 1536
    events:
      - http:
          method: post
          path: scrape
          cors: true
      - stream: ${self:custom.stream}

