service: karate-scraper

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  stage: test
  iamRoleStatements:
    - Effect: Allow
      Action:
      - sns:*
      Resource: arn:aws:sns:*:*:*
  environment:
    region: ${self:provider.region}
    stage: ${self:custom.stage}
    result_arn: ${self:custom.result_arn}

plugins:
  - serverless-webpack

custom:
  webpack: '../../webpack.config.js'
  webpackIncludeModules:
    packagePath: '../../package.json'
  stage: ${opt:stage, self:provider.stage}
  result_stream: ${file(../../config.yml):result_stream}
  result_arn: ${file(../../config.yml):result_arn}

functions:
  scrape:
    handler: handler.scrape
    timeout: 300
    memorySize: 1536
    events:
      - http:
          method: post
          path: scrape
          cors: true
      - stream: ${self:custom.result_stream}

