service:
  name: karate-director

plugins:
  - serverless-pseudo-parameters
  - serverless-step-functions
  - serverless-webpack

custom:
  webpackIncludeModules: true
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  isVersionFunctions-prod: true
  isVersionFunctions-default: false

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  stage: test
  versionFunctions: ${self:custom.isVersionFunctions-${self:custom.stage}, self:custom.isVersionFunctions-default}

functions:
  result:
    handler: handler.result

stepFunctions:
  stateMachines:
    codewarsKatas:
      events:
        - http:
            method: post
            path: codewars/katas
            cors: true
      definition:
        Comment: Scrape Katas Codewars
        StartAt: StartScrape
        States:
          StartScrape:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:custom.prefix}-result"
            End: true
