service: karate-service-api

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  stage: test
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:*
      Resource: arn:aws:dynamodb:*:*:table/*
  environment:
    region: ${self:provider.region}
    task_table: ${self:custom.task_table}
    result_table: ${self:custom.result_table}

plugins:
  - serverless-webpack

custom:
  webpack: '../../webpack.config.js'
  webpackIncludeModules:
    packagePath: '../../package.json'
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  result: ${self:custom.prefix}-result
  task: ${self:custom.prefix}-task
  expression: ${self:custom.prefix}-expression
  task_table: ${self:custom.prefix}-task
  result_table: ${self:custom.prefix}-result

functions:
  addTask:
    handler: handler.addTask
    name: ${self:custom.task}
    events:
      - http:
          method: post
          path: tasks/add
          cors: true

  findExpression:
    handler: handler.findExpression
    name: ${self:custom.expression}
    events:
      - http:
          method: post
          path: expression
          cors: true

  getResult:
    handler: handler.getResult
    name: ${self:custom.result}
    events:
      - http:
          method: get
          path: results/{task_id}
          cors: true

resources:
  Resources:
    ResultTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.result_table}
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.task_table}
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_IMAGE
