service:
  name: karate-scraper

plugins:
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  start:
    seed: true
    inMemory: true
  webpackIncludeModules: true
  prefix: ${self:custom.stage}-${self:service}
  stage: ${opt:stage, self:provider.stage}
  task_table: ${self:custom.prefix}-task
  isVersionFunctions-prod: true
  isVersionFunctions-default: false

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  stage: test
  versionFunctions: ${self:custom.isVersionFunctions-${self:custom.stage}, self:custom.isVersionFunctions-default}
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:*
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/*
  environment:
    region: ${self:provider.region}
    stage: ${self:custom.stage}
    task_table: ${self:custom.task_table}

functions:
  scrape:
    handler: handler.scrape
    timeout: 300
    memorySize: 1536
    events:
      - stream: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/test-karate-scraper-task/stream/2017-11-06T09:42:05.157

  addTask:
    handler: handler.addTask
    name: ${self:custom.prefix}-addTask
    events:
      - http:
          method: post
          path: tasks
          cors: true

  getResult:
    handler: handler.getResult
    name: ${self:custom.prefix}-getResult
    events:
      - http:
          method: get
          path: results/{id}
          cors: true

  findExpression:
    handler: handler.findExpression
    name: ${self:custom.prefix}-findExpression
    events:
      - http:
          method: post
          path: expression
          cors: true

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.task_table}
        KeySchema:
          -
            AttributeName: task_id
            KeyType: HASH
          -
            AttributeName: timestamp
            KeyType: RANGE
        AttributeDefinitions:
          -
            AttributeName: task_id
            AttributeType: S
          -
            AttributeName: timestamp
            AttributeType: N
        ProvisionedThroughput:
          ReadCapacityUnits: 7
          WriteCapacityUnits: 7
        StreamSpecification:
          StreamViewType: NEW_IMAGE
